version: '3.1'
services:

  web:
    container_name: server
    build: .
    command: npm run dev
    volumes:
      - ./:/usr/app/
      - ./node_modules:/usr/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: db://admin:admin@db/test
      PORT: 3001

  db:
    image: postgres
    restart: always
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgreSQL
